### ISSUE TITLE
segfault on Ubuntu 20.04

### ISSUE THREAD

**Issue by kc9jud** [jorio/Bugdom#4]
I'm getting an almost immediate segfault when trying to start Bugdom on Ubuntu MATE 20.04. Here's a stack trace from a debug build:

```
$ gdb build-debug/Bugdom 
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from build-debug/Bugdom...
(gdb) run
Starting program: $HOME/Projects/Bugdom/build-debug/Bugdom 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffef680700 (LWP 678556)]
[New Thread 0x7fffeee7f700 (LWP 678557)]
[New Thread 0x7fffee67e700 (LWP 678558)]
[New Thread 0x7fffede7d700 (LWP 678559)]
[New Thread 0x7fffed478700 (LWP 678560)]
[New Thread 0x7fffed437700 (LWP 678561)]

Thread 1 "Bugdom" received signal SIGSEGV, Segmentation fault.
0x00007ffff55b5c34 in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
(gdb) bt
#0  0x00007ffff55b5c34 in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#1  0x00007ffff577d38e in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#2  0x00007ffff5590789 in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#3  0x00007ffff5591363 in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#4  0x00007ffff4accc79 in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#5  0x00005555556b08a5 in GLDrawContext_New (theView=0x555555f40a80, theDrawContext=0x555555f40d10, clearFlags=0x555555f3f368) at $HOME/Projects/Bugdom/extern/Quesa/Development/Source/Renderers/Common/GLDrawContext.cpp:2195
#6  0x00005555556da693 in QORenderer::Renderer::StartFrame (this=0x555555f3ef00, inView=0x555555f40a80, inDrawContext=0x555555f40d10) at $HOME/Projects/Bugdom/extern/Quesa/Development/Source/Renderers/OpenGL/QOStartAndEnd.cpp:236
#7  0x00005555556471bd in QORenderer::Statics::StartFrameMethod (inView=0x555555f40a80, privateData=0x555555a788e8, inDrawContext=0x555555f40d10) at $HOME/Projects/Bugdom/extern/Quesa/Development/Source/Renderers/OpenGL/QOStatics.cpp:136
#8  0x0000555555625345 in E3Renderer_Method_StartFrame (theView=0x555555f40a80, theDrawContext=0x555555f40d10) at $HOME/Projects/Bugdom/extern/Quesa/Development/Source/Core/System/E3Renderer.cpp:402
#9  0x00005555556372a5 in E3View_StartRendering (theView=0x555555f40a80) at $HOME/Projects/Bugdom/extern/Quesa/Development/Source/Core/System/E3View.cpp:3971
#10 0x00005555555f12ed in Q3View_StartRendering (view=0x555555f40a80) at $HOME/Projects/Bugdom/extern/Quesa/Development/Source/Core/Glue/QD3DView.cpp:289
#11 0x00005555555a94d1 in QD3D_DrawScene (setupInfo=0x55555603a4a0, drawRoutine=0x5555555c8c1f <DrawObjects>) at $HOME/Projects/Bugdom/src/QD3D/QD3D_Support.c:628
#12 0x00005555555b8a8a in DoPangeaLogo () at $HOME/Projects/Bugdom/src/Screens/MiscScreens.c:373
#13 0x00005555555c78dc in GameMain () at $HOME/Projects/Bugdom/src/System/Main.c:900
#14 0x0000555555564c18 in CommonMain (argc=1, argv=0x7fffffffc368) at $HOME/Projects/Bugdom/src/Main.cpp:140
#15 0x0000555555564d99 in main (argc=1, argv=0x7fffffffc368) at $HOME/Projects/Bugdom/src/Main.cpp:162
(gdb) 
```

This looks like it could be an OpenGL/driver problem, but I'm not sure. It's possibly related to [this bug](https://bugs.launchpad.net/ubuntu/+source/mesa/+bug/1877879).

**Comment by kc9jud** [comment]
I can confirm it's an upstream bug with OpenGL. I'll add a note to the readme.

**Comment by jpenguin** [comment]
My VM runs Ubuntu Mate 20.04, run Bugdom fine with no 3D acceleration.  https://filedn.com/lHGef0SOQKnBTotcJeEfshJ/Games/Bugdom/Bugdom.static.xz is a static build, still needs data.  https://filedn.com/lHGef0SOQKnBTotcJeEfshJ/Games/Bugdom/Bugdom.tar.xz  is a dynamic build done on Tumbleweed that seems to run fine on Ubuntu

**Comment by kc9jud** [comment]
Yeah, this is absolutely an upstream driver bug in Ubuntu -- the same bug causes Steam to crash, and the same workaround applies to both. It makes sense that it wouldn't show up in a virtualized environment.

**Comment by jorio** [comment]
Sorry, I can't do much about a GPU driver bug that affects most OpenGL applications (not Bugdom specifically).
